apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: newbank-ingress
spec:
  rules:
  - host: newbank.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ui-service
            port:
              number: 80
